FROM node:12.2.0-alpine

# install simple http server for serving static content
RUN npm install -g http-server

WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json /app/package.json

RUN npm install
RUN npm install @quasar/cli -g

COPY . .

RUN npm run build

EXPOSE 8081
CMD [ "http-server", "dist/spa", "--port", "8081" ]
# CMD ["npm", "run", "serve", "--port 8081"] # takes too long