schedules:
- cron: "1 23 12,26 * Sun"
  displayName: Tuesday sprint start
  branches:
    include:
    - master
    - develop

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
   pip install $(GIT)
   python DevOps/premissions.py $USERNAME $PASS push
  env:
    USERNAME: $(username)
    PASS: $(pass)
