# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
schedules:
- cron: "1 23 * * Sun"
  displayName: Monday sprint end
  branches:
    include:
    - master
    - develop

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
   pip install $(GIT)
   python DevOps/premissions.py $USERNAME $PASS pull
  env:
    USERNAME: $(username)
    PASS: $(pass)
