version: '3.8'
services:
  user_microservice:
    image: psw_usermicroservice
    build: 
      context: WEB_Backend/UserMicroservice
      dockerfile: Dockerfile.local
    ports:
      - "8081:8081"
    volumes:
      - user_microservice_data:/var/lib/userdata/data
    restart: on-failure
    depends_on: 
      - db
    networks:
      - compose_network
  
  db:
    image: psw_mysqldb
    ports:
      - "5433:5432"
    environment:
       DATABASE_HOST: localhost
       DATABASE_PORT: 3306
       DATABASE_SCHEMA: HealthClinicDB
       DATABASE_USERNAME: root
       DATABASE_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - compose_network
  
  api_gateway:
    image: psw_apigateway
    build: 
      context: WEB_Backend/APIGateway
      dockerfile: Dockerfile.local
    ports:
      - "8082:8082"
    restart: on-failure
    depends_on: 
      - db
    networks:
      - compose_network

  client:
    image: psw_client
    build: 
      context: WEB_Frontend/web_frontend
      dockerfile: Dockerfile.local
    ports:
      - "8083:8083"
    restart: on-failure
    depends_on: 
      - db
    networks:
      - compose_network

volumes:
  user_microservice_data:
  db_data:

networks:
  compose_network:
    name: compose_network
    driver: bridge